### PR TITLE
fixed Add Aria: separator#31

### PR DESCRIPTION
**Pull request by syedareehaquasar**
# What Changed
Added snippet for separator

# Why
fixes Add Aria: separator#31
fixes: #31 
easy properties with the default value for separator role for HR tag!

Todo:
- [ ] Add Semantic Version Label 
- [X] Add tests/ Tested
- [X] Add docs

### CODE REVIEW

**Review by kendallgassner — COMMENTED** [review]
❇️ ❇️ 

Can you add your description of your snippet to the `readme` file as well

**Comment by syedareehaquasar** [comment]
sure on it!

**Comment by syedareehaquasar** [comment]
done

**Comment by syedareehaquasar** [comment]
Resolved merge conflict!

**Review by kendallgassner — APPROVED** [review]
⭐ ⭐

**Pull request merged**
